/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    blocInfo: BlocInfo;
    category: Category;
    color: Color;
    media: Media;
    product: Product;
    sizeGuide: SizeGuide;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    blocInfo: BlocInfoSelect<false> | BlocInfoSelect<true>;
    category: CategorySelect<false> | CategorySelect<true>;
    color: ColorSelect<false> | ColorSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
    sizeGuide: SizeGuideSelect<false> | SizeGuideSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    message: Message;
    nav: Nav;
  };
  globalsSelect: {
    message: MessageSelect<false> | MessageSelect<true>;
    nav: NavSelect<false> | NavSelect<true>;
  };
  locale: 'en' | 'fr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocInfo".
 */
export interface BlocInfo {
  id: string;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  description: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color".
 */
export interface Color {
  id: string;
  name: string;
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: string;
  category: string | Category;
  title: string;
  slug?: string | null;
  description: string;
  images?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  sizeGuide?: (string | null) | SizeGuide;
  colors?:
    | {
        default?: boolean | null;
        color: string | Color;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  colorsSecondary?:
    | {
        default?: boolean | null;
        color: string | Color;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  options?:
    | {
        title: string;
        values?:
          | {
              title: string;
              delta?:
                | {
                    type: 'price' | 'weight' | 'temperature' | 'volume' | 'time';
                    value: number;
                    unit: '€' | '%';
                    id?: string | null;
                  }[]
                | null;
              defaultValue?: boolean | null;
              /**
               * Facultatif. Image permettant d'illustrer cette option.
               */
              image?: (string | null) | Media;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Facultatif. Ce texte s'affichera en tooltip au survol de l'option.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  advanced?:
    | {
        title: string;
        values?:
          | {
              title: string;
              delta?:
                | {
                    type: 'price' | 'weight' | 'temperature' | 'volume' | 'time';
                    value: number;
                    unit: '€' | '%';
                    id?: string | null;
                  }[]
                | null;
              defaultValue?: boolean | null;
              /**
               * Facultatif. Image permettant d'illustrer cette option.
               */
              image?: (string | null) | Media;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Facultatif. Ce texte s'affichera en tooltip au survol de l'option.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  technicalInfos?:
    | {
        /**
         * Remplace le titre par défaut du bloc d'information pour ce produit.
         */
        title?: string | null;
        info?: (string | BlocInfo)[] | null;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        /**
         * Remplace le titre par défaut du bloc d'information pour ce produit.
         */
        title?: string | null;
        info?: (string | BlocInfo)[] | null;
        id?: string | null;
      }[]
    | null;
  care?:
    | {
        /**
         * Remplace le titre par défaut du bloc d'information pour ce produit.
         */
        title?: string | null;
        info?: (string | BlocInfo)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizeGuide".
 */
export interface SizeGuide {
  id: string;
  title: string;
  rows: number;
  cols: number;
  table?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'blocInfo';
        value: string | BlocInfo;
      } | null)
    | ({
        relationTo: 'category';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'color';
        value: string | Color;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'product';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'sizeGuide';
        value: string | SizeGuide;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocInfo_select".
 */
export interface BlocInfoSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category_select".
 */
export interface CategorySelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color_select".
 */
export interface ColorSelect<T extends boolean = true> {
  name?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  slug?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  sizeGuide?: T;
  colors?:
    | T
    | {
        default?: T;
        color?: T;
        image?: T;
        id?: T;
      };
  colorsSecondary?:
    | T
    | {
        default?: T;
        color?: T;
        image?: T;
        id?: T;
      };
  options?:
    | T
    | {
        title?: T;
        values?:
          | T
          | {
              title?: T;
              delta?:
                | T
                | {
                    type?: T;
                    value?: T;
                    unit?: T;
                    id?: T;
                  };
              defaultValue?: T;
              image?: T;
              value?: T;
              id?: T;
            };
        description?: T;
        id?: T;
      };
  advanced?:
    | T
    | {
        title?: T;
        values?:
          | T
          | {
              title?: T;
              delta?:
                | T
                | {
                    type?: T;
                    value?: T;
                    unit?: T;
                    id?: T;
                  };
              defaultValue?: T;
              image?: T;
              value?: T;
              id?: T;
            };
        description?: T;
        id?: T;
      };
  technicalInfos?:
    | T
    | {
        title?: T;
        info?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        title?: T;
        info?: T;
        id?: T;
      };
  care?:
    | T
    | {
        title?: T;
        info?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizeGuide_select".
 */
export interface SizeGuideSelect<T extends boolean = true> {
  title?: T;
  rows?: T;
  cols?: T;
  table?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message".
 */
export interface Message {
  id: string;
  message: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (string | null) | Media;
  active?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: string;
  items: {
    title: string;
    image?: (string | null) | Media;
    category: (string | Category)[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message_select".
 */
export interface MessageSelect<T extends boolean = true> {
  message?: T;
  image?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        image?: T;
        category?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}